---
title: Powerful patterns
hero_image: images/banner.png
description:
  Create a piece of inspirational art that can be scaled using repeated
  patterns
meta_title: Python coding projects for kids and teens | Powerful patterns
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Create a piece of inspirational art with Python using repeated patterns.
version: 4
listed: false
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged
  - title: Step 3
    completion:
      - internal
  - title: Step 4
    completion:
      - external
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8
    challenge: true